### PR TITLE
Change from recursive to while loop

### PR DESCRIPTION
**Pull request by MadcapJake**
### Changes
- Better guarding of infinite loop
- Windows HOMEPATH support

Note: maybe this should be included optionally as perl6 will loop out-of-control if their is a circular dependency.  On my machine perl6 created hundreds of `moar` processes until I lost any ability to interact with my computer.  One time, I was able to get in to a terminal and start killing these but it would just infinitely create more and I merely slowed down the process.

Another option would be to search all files for `use` statements and check for circular dependencies before running `perl6 -c`.  This could be a nifty addition to this package: check dependencies, check for circular dependencies, and maybe even write to the `META6.json` file.

### CODE REVIEW

**Comment by azawawi** [comment]
Could you provide a minimal Perl 6 script of this bug to reproduce?

**Comment by MadcapJake** [comment]
I really don't want to try because I'm so tired of restarting my machine :stuck_out_tongue_closed_eyes: 

But I'd guess [this](https://gist.github.com/MadcapJake/9b8d36c0cef1b7062b7c) would cause it.

**Comment by azawawi** [comment]
Thanks for your time. So if i understand correctly, we're fixing this because of a rakudo bug, right?

**Comment by MadcapJake** [comment]
lol well this PR doesn't fix anything, just a more reasonable and cross-platform while loop

**Comment by MadcapJake** [comment]
but managing dependencies could be a neat feature, I mean.  Dart's [dartlang](https://atom.io/packages/dartlang) package supports all sorts of package/dependency management stuff and it's quite nice!

**Comment by azawawi** [comment]
Thanks. I am converting it to ES6 :+1:

**Pull request merged**
